#!/bin/sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/common.sh

PAYLOAD=$(mktemp /tmp/resource-in.XXXXXX)

cat > "$PAYLOAD" <&0

parse_source_config

[ -z "$VERSION" ] && VERSION='none'

jq -n "{
  version: {
    timestamp: \"$VERSION\"
  }
}" >&3