#!/bin/sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/common.sh

PAYLOAD=$(mktemp /tmp/resource-out.XXXXXX)

cat > "$PAYLOAD" <&0

parse_source_config
parse_out_params

VERSION="$(jq -n "{version:{time:\"$(date -Iseconds)\"}}")"

SOURCE_DIR=$1
cd $SOURCE_DIR

lftp -c "open $URL; mirror -v -R $SOURCE_DIR/$RELATIVE_DIR . ;"

echo "$VERSION" >&3